### ISSUE TITLE
NTLM hashes not returning with --lsa

### ISSUE THREAD

**Issue by ama21n** [byt3bl33d3r/CrackMapExec#290]
## Steps to reproduce
Running cme over several hosts returns only the cleartext passwords from memory, not the NTLM hashes which can be very useful for PTH in case clear text pw's are unavailable. RDP'ing and running mimikatz returns both types.

## Command string used
cme $ip -d $dom -u $user -p $pw --lsa

## CME Version (cme --version)
3.1.5 - 'Smidge'

## OS
Linux kali 4.4.0-kali1-686 #1 SMP Debian 4.4.2-3kali1 (2016-02-23) i686 GNU/Linux

## Target OS
Mixed... mostly Win 10 / Server 2016

**Comment by awsmhacks** [comment]
This isnt really what the module is looking for. LSA Secrets _might_ contain auto-login service accounts, vpn creds, stored IE passwords in older systems but you def wont find domain NTLM hashes here, certainly not on win10.  
On some machines you might find cached domain credentials but most likely those wont be useful either, unless you figure out how to obtain the NL$KM key and decrypt them.  
Check out this article for a bit more on LSA Secrets and what you can get -> https://moyix.blogspot.com/2008/02/decrypting-lsa-secrets.html

Mimikatz is a different thing, --lsa is using secretsdump.py from impacket. If you want domain ntlm hashes why not run the mimikatz module? (well, in a version of CME where that works ;) Or procdump lsass and take it offline to run mimikatz?  

You can also try using --sam and grabbing local hashes. You could pass-the-hash with those, provided they are shared with another system.

**Comment by ama21n** [comment]
Many thanks awsmhacks! I'm only really after domain hashes/passwords. 
Appears the mscache hashes are already decrypted using the gathered NL$KM key. Tried using mimikatz module (both on stable and bleeding edge), but on win10 devices (Windows 10 Pro 17763), all I receive is "Waiting on 1 host(s)". I presume this is defender blocking access somehow?

On win8.1, ntlm hashes don't get spat out to screen (which would be handy), but they do get saved to /root/.cme/logs/ for further inspection/retrieval.
Is there another command line module/tool that could be used on win10 to procdump lsass and take it offline to run mimikatz?

**Comment by awsmhacks** [comment]
That's not defender stopping you, it's the (now) broken PSInject.ps1 script. after the 1804 win10 update a command psinject uses (GetProcAddress) became ambiguous. There is a PR out to fix this -  https://github.com/EmpireProject/PSInject/pull/2 but there are other issues that are working against you when trying to run modules. These probably wont get fixed in this version of CME, i believe development has started, or at least is planned to start, on a python3 implementation of CME that will fix a bunch of stuff. Just not worth hacking together code to make it work how it is now just to accomadate for latest win10.  
  
Procdump is just a part of sysinternals - https://docs.microsoft.com/en-us/sysinternals/downloads/procdump - you could load it from https://live.sysinternals.com onto the host and run it on lsass, then download the result .DMP file. there's probably 10 ways to accomplish this depending on the scenario, so i'll leave that as an exercise for ya :)  
  
  P.S. don't forget, the local administrator account is often set with the same password on multiple machines, admins build new workstations from the same golden image to save time. sometimes you can get further with local accounts than non-privileged domain accounts.    
  
also, i think we can consider this issue closed?
