### ISSUE TITLE
--continue-on-success Gets "ACCESS_DENIED" After First Success

### ISSUE THREAD

**Issue by sctf2020** [byt3bl33d3r/CrackMapExec#321]
## Steps to reproduce

`cme smb dc01.storm.ctf -u users.txt -p welcome1 --continue-on-success`
I'd post the output but it's of a client's network. --continue-on-success has never worked for me but I could really use it!

**Comment by n00py** [comment]
Yep, I've had the same issue also.

**Comment by squid22** [comment]
I have the same issue... can you confirm if within the password file welcome1, you have a password with characters like !#$@%$(?
It get errors on the smb and winrm module. I been testing it on a hackTheBox machine that I know the username and password is 100% accurate and it fails because the contents of the file has special characters... when I surround the password with single quotes or double quotes on the file, the errors are gone but of course the password doesn't match ...

**Comment by mpgn** [comment]
Working on Windows 10 but not on Windows server 2016. I will look into it but it's probably related to impacket

**Comment by mpgn** [comment]
It's linked to the smb signing, here is an example if smb signing is disabled

![image](https://user-images.githubusercontent.com/5891788/80287154-2197d500-8730-11ea-9b3f-06ddd934814b.png)

**Comment by mpgn** [comment]
Ok I push a fix

![image](https://user-images.githubusercontent.com/5891788/81475154-abed3800-920a-11ea-9a45-4b440050e6f5.png)
