### ISSUE TITLE
Bypaas Windows defender?

### ISSUE THREAD

**Issue by abid28june** [byt3bl33d3r/CrackMapExec#331]
is there any way to bypaas defender on remote system using CME or any other tool, because CME gets blocked by defender when execution MimiKatz or powershell command.

**Comment by TheCyberTecky** [comment]
This is where using Linux or even Windows Subsystem Linux 2 (WSL2) makes it so much easier but we all have or preferences.  From Windows 10, you should just be able to add a Windows Defender 'Exclusion' to the 'CrackMapExecWin.exe' file, and possibly the entire folder archive where that file is located.

Click the Windows 'Start' menu > type, 'Exclusion' then > 'Virus & threat protection > under "Virus & threat protection settings, click "Manage settings" > Scroll down to 'Exclusions, click "Add or remove exclusions, > click the 'Add an exclusion' button then begin excluding what you need, e.g., file, folder, etc.

Hope this helps!

On Feb 1, 2020, at 7:38 AM, abid28june <notifications@github.com<mailto:notifications@github.com>> wrote:

is there any way to bypaas defender on remote system using CME or any other tool, because CME gets blocked by defender when execution MimiKatz or powershell command.

**Comment by abid28june** [comment]
How do I do this if I don’t have access to the target system? My question was being restricted with cme how would u able to bypass defender in order to execute mimikatz nd powershell command because it block our cme request on windows 2016 nd windows 10, hope u understand.

**Comment by n00py** [comment]
OP is talking about CME modules on remote (target) systems, not his own system.

And to answer the question. there is no solution aside from using custom tooling.  Running "Invoke-Mimikatz" will never work on Windows 10.  Don't use the built in modules that rely on powershell.

**Comment by mpgn** [comment]
Closing since it's not related to CME
