### ISSUE TITLE
Different requirements in requirements.txt and setup.py

### ISSUE THREAD

**Issue by maaaaz** [byt3bl33d3r/CrackMapExec#348]
Hello there again,

`requirements.txt` and `setup.py` do not contain the same prerequisites !

Cheers.

**Comment by byt3bl33d3r** [comment]
Heya, 
That's intentional. There's a common misunderstanding that `requirements.txt` and the dependencies specified in `install_requires` in the `setup.py` should be the same. They shouldn't for a very good reason.

From the [official Python docs](https://packaging.python.org/discussions/install-requires-vs-requirements/#requirements-files):

>Whereas install_requires requirements are minimal, requirements files often contain an exhaustive listing of pinned versions for the purpose of achieving repeatable installations of a complete environment.

`requirements.txt` gets automatically generated by `pipenv` with all dependency and sub-dependency pinned versions. So while they might seem out of sync, they really aren't.

**Comment by maaaaz** [comment]
Okay !
The bad point is that, by tradition (and ignorance), a lot of people will do a `pip install -r requirements.txt` and then get stucked with strict non-upgradeable lib versions.
