### ISSUE TITLE
--mimikatz not working

### ISSUE THREAD

**Issue by schniggie** [byt3bl33d3r/CrackMapExec#61]
Hey,

I got a problem with the --mimikatz option. When I try to execute mimikatz on the remote system, the executing hangs after: "Executed command via WMIEXEC". That happen on all systems here. Several other options like -x CMD are working just fine. How is mimikatz executed on the remote system or how it is transfered to the remote system? Maybe any firewall restriction are responsible for that?

**Comment by byt3bl33d3r** [comment]
@schniggie gonna need more info, target OS & architecture and a packet capture would be awesome. Just tested it on my systems and it seems to be working fine

**Comment by byt3bl33d3r** [comment]
Closing this for now as it seems to be working for me, comment below if you have time to give me some more info

**Comment by thomasRousseau** [comment]
Hi there, I know it has been closed as no further info was provided, but I'm facing the same issue. My guess is that the target system doesnt have the proper proxy settings in order to download the mimikatz payload from the Kali (does it setup a web server and tell the target host to go and download it ?). Anyhow, I guess there might be some way to send mimikatz via -x CMD as à one liner, but that is beyond my personal expertise
