### ISSUE TITLE
State of CrackMapExec

### ISSUE THREAD

**Issue by NeffIsBack** [byt3bl33d3r/CrackMapExec#799]
I have a few questions:

- Why is the repo unarchived?
- Why does this suddenly happen at the time @mpgn leaves porchetta?
- Who will continue the official repo, from my point of view was @mpgn the maintainer now for years?

- If you really plan to start developing cme again how is it planned to be released? Fully open source? Half open source with porchetta or fully commercialized?

**Comment by Marshall-Hallenbeck** [comment]
@byt3bl33d3r a bunch of us are confused on where development should occur and who the main maintainer is. Can you help clear up where we should be developing and who will be merging code into the main branch & doing releases?

**Comment by byt3bl33d3r** [comment]
All further development will occur on this repository and I will be maintaining CME for the foreseeable future.

The repo was un-archived because I will be continuing development on CME as mpgn can no longer maintain this project. 

As before, CME releases will be done according to Porchetta's Sponsorware model: all new features and updates will first be made available to subscribers and then they'll be made public here after a time delay.

(If anyone seeing this comment is interested in subscribing go to https://porchetta.industries)

If you make a meaningful contribution to the public version of CME here, you'll be given a challenge coin and/or lifetime access to the private repository made available to subscribers (for free) depending on how meaningful the contribution is.

**Comment by byt3bl33d3r** [comment]
I've opened up discussions in this repository, feel free to open a thread there about this if more clarification is needed.

**Comment by noraj** [comment]
Discussion link: https://github.com/Porchetta-Industries/CrackMapExec/discussions/801
